/**
 * Catálogo local de nombres de instrumentos argentinos.
 *
 * BYMADATA (panel v2) NO incluye el nombre/descripción de los instrumentos
 * (description/securityDesc vienen vacíos) y los endpoints de mercado de
 * IOL v2 están caídos (verificado 13/08/2026). Este mapa cubre los
 * instrumentos más comunes (CEDEARs, acciones líderes y bonos) para que
 * la app muestre el nombre de la empresa. Los que no estén en el mapa
 * muestran solo el símbolo.
 */
export const INSTRUMENT_NAMES: Record<string, string> = {
  // ===== CEDEARs (BCBA) =====
  AAPL: "Apple Inc. CEDEAR",
  MSFT: "Microsoft Corp. CEDEAR",
  GOOGL: "Alphabet Inc. CEDEAR",
  GOOG: "Alphabet Inc. CEDEAR",
  AMZN: "Amazon.com Inc. CEDEAR",
  NVDA: "NVIDIA Corp. CEDEAR",
  NVDAC: "NVIDIA Corp. CEDEAR (C)",
  NVDAD: "NVIDIA Corp. CEDEAR (D)",
  META: "Meta Platforms Inc. CEDEAR",
  TSLA: "Tesla Inc. CEDEAR",
  NFLX: "Netflix Inc. CEDEAR",
  KO: "Coca-Cola Co. CEDEAR",
  DIS: "Walt Disney Co. CEDEAR",
  SPY: "SPDR S&P 500 ETF CEDEAR",
  QQQ: "Invesco QQQ Trust CEDEAR",
  V: "Visa Inc. CEDEAR",
  MA: "Mastercard Inc. CEDEAR",
  JPM: "JPMorgan Chase & Co. CEDEAR",
  PEP: "PepsiCo Inc. CEDEAR",
  MCD: "McDonald's Corp. CEDEAR",
  SBUX: "Starbucks Corp. CEDEAR",
  INTC: "Intel Corp. CEDEAR",
  AMD: "Advanced Micro Devices CEDEAR",
  CSCO: "Cisco Systems CEDEAR",
  ORCL: "Oracle Corp. CEDEAR",
  CRM: "Salesforce Inc. CEDEAR",
  ADBE: "Adobe Inc. CEDEAR",
  IBM: "IBM Corp. CEDEAR",
  XOM: "Exxon Mobil Corp. CEDEAR",
  CVX: "Chevron Corp. CEDEAR",
  PFE: "Pfizer Inc. CEDEAR",
  JNJ: "Johnson & Johnson CEDEAR",
  PG: "Procter & Gamble CEDEAR",
  WMT: "Walmart Inc. CEDEAR",
  BA: "Boeing Co. CEDEAR",
  CAT: "Caterpillar Inc. CEDEAR",
  GE: "GE Aerospace CEDEAR",
  F: "Ford Motor Co. CEDEAR",
  GM: "General Motors CEDEAR",
  BABA: "Alibaba Group CEDEAR",
  TSM: "Taiwan Semiconductor CEDEAR",
  MELI: "MercadoLibre Inc. CEDEAR",
  C: "Citigroup Inc. CEDEAR",
  BAC: "Bank of America Corp. CEDEAR",
  WFC: "Wells Fargo & Co. CEDEAR",
  GS: "Goldman Sachs Group Inc. CEDEAR",
  MS: "Morgan Stanley CEDEAR",
  BRKB: "Berkshire Hathaway Inc. Class B CEDEAR",
  COST: "Costco Wholesale Corp. CEDEAR",
  AVGO: "Broadcom Inc. CEDEAR",
  QCOM: "Qualcomm Inc. CEDEAR",
  TXN: "Texas Instruments Inc. CEDEAR",
  NKE: "Nike Inc. CEDEAR",
  HD: "The Home Depot Inc. CEDEAR",
  UNH: "UnitedHealth Group Inc. CEDEAR",
  ABBV: "AbbVie Inc. CEDEAR",
  MRK: "Merck & Co. Inc. CEDEAR",
  LLY: "Eli Lilly and Company CEDEAR",
  PYPL: "PayPal Holdings Inc. CEDEAR",
  UBER: "Uber Technologies Inc. CEDEAR",
  SHOP: "Shopify Inc. CEDEAR",
  ABNB: "Airbnb Inc. CEDEAR",
  // ===== Acciones líderes (BCBA) =====
  GGAL: "Grupo Financiero Galicia",
  YPFD: "YPF S.A.",
  PAMP: "Pampa Energía",
  APBR: "Aeropuertos Argentina 2000",
  BMA: "Banco Macro",
  BBAR: "Banco BBVA Argentina",
  ALUA: "Aluar",
  CEPU: "Central Puerto",
  COME: "Sociedad Comercial del Plata",
  CRES: "Cresud",
  EDN: "Edenor",
  LOMA: "Loma Negra",
  METR: "Metrogas",
  SUPV: "Grupo Supervielle",
  TECO: "Telecom Argentina",
  TGSU4: "TGS",
  TXAR: "Ternium Argentina",
  TRAN: "Transportadora de Gas del Sur",
  VALO: "Banco de Valores",
  VIST: "Vista Energy",
  MIRG: "Mirgor",
  HARG: "Holcim Argentina",
  IRSA: "IRSA",
  // ===== Bonos (BCBA) =====
  AL30: "Bono AL30 (USD ley NY)",
  AL29: "Bono AL29 (USD ley NY)",
  AL41: "Bono AL41 (USD ley NY)",
  AE38: "Bono AE38 (USD)",
  GD30: "Global 2030 (USD)",
  GD35: "Global 2035 (USD)",
  GD38: "Global 2038 (USD)",
  GD41: "Global 2041 (USD)",
  GD46: "Global 2046 (USD)",
};
